AWSTemplateFormatVersion: 2010-09-09
Description: API Gateway Lambda using an OpenApi defintion

Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: OpenApi Example Api
      Description: Example API Gateway using OpenApi defintion
      FailOnWarnings: true
      Body:
        swagger: 2.0
        info:
          version: 2016-08-18T18:08:34Z
          title: 'OpenApi Example'
        basePath: '/'
        schemes:
          - 'https'
        paths:
          hello:
            post:
              produces:
                - 'application/json'
              responses:
                '200':
                  description: '200 response'
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                uri: !Sub
                  - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${HelloFunctionName}/invocations'
                  - { HelloFunctionName: !Ref HelloLambda}
                passthroughBehavior: 'when_no_match'
                httpMethod: 'POST'
                type: 'aws_proxy'

  HelloLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: swagger-golang-api-example
        S3Key: lambda.zip
      Role: !GetAtt InvocationRole.Arn
      Runtime: go1.x
      Handler: main

  InvocationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'

  SampleApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref HelloLambda
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub 
        - "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*/POST/hello"
        - { ApiId: !Ref ApiGateway }
